spring:
    application:
        name: keenness-admin

server:
    port: 8083

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        serviceUrl:
           defaultZone: http://localhost:8761/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


#redis
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: 192.168.36.131
    port:  6379
    password:
    timeout: 2000